dataset_path: "data/"
output_model_path: "model.pkl"
metric_path: "metrics.json"
splitting_params:
  val_size: 0.1
  random_state: 42
classifier_params:
  model_type: "LogisticRegression"
  max_iter: 500
feature_params:
  numerical_features:
    - "alcohol"
    - "malic_acid"
    - "ash"
    - "alcalinity_of_ash"
    - "magnesium"
    - "total_phenols"
    - "flavanoids"
    - "nonflavanoid_phenols"
    - "proanthocyanins"
    - "color_intensity"
    - "hue"
    - "od280/od315_of_diluted_wines"
    - "proline"
