apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-inference-deployment-blue-green
  labels:
    app: online-inference
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      name: online-inference-deployment-blue-green
      labels:
        app: online-inference
    spec:
      containers:
        - image: ivanovnikolayyy/made_ml_in_prod:latest
          name: online-inference-deployment-blue-green
          ports:
            - containerPort: 80
