apiVersion: v1
kind: Pod
metadata:
  name: online-inference-simple
  labels:
    app: online-inference
spec:
  containers:
    - name: online-inference-simple
      image: ivanovnikolayyy/made_ml_in_prod:latest
      ports:
        - containerPort: 80
