apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-replicaset
  labels:
    app: online-inference-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-inference-replicaset
  template:
    metadata:
      name: online-inference-replicaset
      labels:
        app: online-inference-replicaset
    spec:
      containers:
        - image: ivanovnikolayyy/made_ml_in_prod:latest
          name: online-inference-replicaset
          ports:
            - containerPort: 80
